# Generated by Django 4.2.6 on 2024-04-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default='1famjxgj4wzhj0ks4zkj', editable=False, max_length=20),
        ),
    ]
