# Generated by Django 4.2.6 on 2024-04-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_ref_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default='a2ev1czxgi0zw1y28zpb', editable=False, max_length=20),
        ),
    ]
