# Generated by Django 4.2.6 on 2024-04-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_ref_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default='0jb4rgq9ax8e4dyrv4q6', editable=False, max_length=20),
        ),
    ]
