# Generated by Django 4.2.6 on 2024-04-13 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwoodiqueuserprofile',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='artwoodiqueuserprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='artwoodiqueuserprofile',
            name='one_click_purchasing',
        ),
        migrations.RemoveField(
            model_name='artwoodiqueuserprofile',
            name='stripe_customer_id',
        ),
    ]
