# Generated by Django 4.2.6 on 2024-04-13 20:06

import django.core.validators
from django.db import migrations, models
import project.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_artwoodiqueuserprofile_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwoodiqueuserprofile',
            name='name',
        ),
        migrations.AddField(
            model_name='artwoodiqueuserprofile',
            name='first_name',
            field=models.CharField(default='ivan', max_length=30, validators=[django.core.validators.MinLengthValidator(2), project.accounts.models.validate_only_letters]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artwoodiqueuserprofile',
            name='last_name',
            field=models.CharField(default='Ivanov', max_length=30, validators=[django.core.validators.MinLengthValidator(2), project.accounts.models.validate_only_letters]),
            preserve_default=False,
        ),
    ]
