# Generated by Django 4.2.6 on 2024-04-14 07:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_artwoodiqueuserprofile_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwoodiqueuserprofile',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
