# Generated by Django 4.2.6 on 2024-04-14 07:56

import django.core.validators
from django.db import migrations, models
import project.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_artwoodiqueuserprofile_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwoodiqueuserprofile',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), project.accounts.models.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='artwoodiqueuserprofile',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
