# Generated by Django 4.2.6 on 2024-04-14 08:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_artwoodiqueuserprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwoodiqueuserprofile',
            name='username',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
