# Generated by Django 4.2.6 on 2023-10-27 12:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import project.main.models
import project.shared.functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('subheading', models.CharField(max_length=125)),
                ('description', models.TextField(max_length=400)),
                ('material', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=project.main.models.upload_image_product_url)),
                ('views', models.IntegerField(default=0)),
                ('in_stock', models.BooleanField(default=True)),
                ('price', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(102410241024.0), django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rating',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=project.shared.functions.upload_other_images_product_url)),
                ('name', models.CharField(max_length=125)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
            options={
                'db_table': 'images',
            },
        ),
    ]
