# Generated by Django 4.2.6 on 2024-03-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='product',
            name='subheading',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=400),
        ),
    ]
