# Generated by Django 4.2.6 on 2024-04-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_order_billing_address_remove_order_coupon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='item',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='item',
            field=models.ManyToManyField(to='main.product'),
        ),
    ]
