# Generated by Django 4.2.6 on 2024-04-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_itemlike_item_remove_itemlike_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Living Table', 'Living Table'), ('Coffe Table', 'Coffe Table'), ('Dining Table', 'Dining Table')], default='undefined', max_length=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='undefined', max_length=3),
        ),
    ]
