# Generated by Django 4.2.6 on 2024-04-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_product_type_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(choices=[('Oak', 'Oak'), ('Cherry', 'Cherry'), ('Pine', 'Pine'), ('Walnut', 'Walnut'), ('Mulberry', 'Mulberry')], default='undefined', max_length=8),
        ),
    ]
