# Generated by Django 4.2.6 on 2024-04-21 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_product_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='ProductRating',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
