# Generated by Django 4.2.6 on 2024-04-21 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_userprofile_user_delete_productrating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='label',
        ),
    ]
